import type { Metadata } from "next";
import { Geist, Geist_Mono, Climate_Crisis } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/layouts/LayoutProvider";
import Navbar from "./components/navbar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const climateCrisis = Climate_Crisis({
  variable: "--font-climate-crisis",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={` scroll-smooth ${geistSans.variable} ${geistMono.variable} ${climateCrisis.variable}  antialiased`}
      >
        <LayoutProvider>
          <Navbar />
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
